<a href="https://colab.research.google.com/github/mebirtukan/newgit/blob/main/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from scipy.io import loadmat
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.preprocessing.sequence import  TimeseriesGenerator
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import tensorflow as tf

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving emvic.data to emvic (1).data


In [ ]:
data=pd.read_csv("emvic.data",sep="\t",header=None)
data

In [ ]:
len(x)

416

In [ ]:
y.shape

In [ ]:
x.shape

(416, 12288)

In [ ]:
x=data.iloc[:,1:12289].values
y=data.iloc[:, 0].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.25)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
from sklearn import svm
svm.SVC(kernel='linear')
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

         a25       0.72      0.91      0.81        32
         a28       0.60      0.82      0.69        11
         a29       0.23      1.00      0.38         3
         a32       0.67      0.43      0.52        14
         a37       0.67      0.50      0.57        12
         a40       0.89      0.73      0.80        11
         a41       1.00      0.14      0.25        14
         a42       0.29      0.29      0.29         7

    accuracy                           0.62       104
   macro avg       0.63      0.60      0.54       104
weighted avg       0.71      0.62      0.61       104

[[29  0  1  2  0  0  0  0]
 [ 2  9  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0]
 [ 4  1  1  6  0  0  0  2]
 [ 1  0  2  1  6  1  0  1]
 [ 2  1  0  0  0  8  0  0]
 [ 1  3  4  0  2  0  2  2]
 [ 1  1  2  0  1  0  0  2]]


In [ ]:
correct = 0;
#predictedLabels = KNeighborsClassifier.predict(x_test, y_train)
for i in range(len(x)):
  print(y_test[i],"->",y_pred[i],end=' ')
  if(y_test[i]==y_pred[i]):
    correct = correct + 1; print('OK')
  else:
      print('error!!!')
print("Correct: {} of {} accuracy = {:.2f}" .format(correct,len(x_test),correct/len(x_test)))

a42 -> a29 error!!!
a28 -> a28 OK
a41 -> a42 error!!!
a41 -> a28 error!!!
a28 -> a28 OK
a25 -> a25 OK
a40 -> a25 error!!!
a40 -> a40 OK
a32 -> a25 error!!!
a25 -> a25 OK
a28 -> a28 OK
a25 -> a32 error!!!
a28 -> a25 error!!!
a25 -> a25 OK
a37 -> a37 OK
a32 -> a32 OK
a42 -> a28 error!!!
a25 -> a25 OK
a40 -> a40 OK
a32 -> a29 error!!!
a25 -> a25 OK
a29 -> a29 OK
a41 -> a25 error!!!
a32 -> a32 OK
a32 -> a25 error!!!
a40 -> a40 OK
a41 -> a42 error!!!
a32 -> a32 OK
a28 -> a25 error!!!
a25 -> a25 OK
a37 -> a42 error!!!
a41 -> a29 error!!!
a25 -> a25 OK
a40 -> a40 OK
a25 -> a25 OK
a40 -> a40 OK
a25 -> a25 OK
a25 -> a25 OK
a41 -> a28 error!!!
a25 -> a25 OK
a25 -> a25 OK
a25 -> a25 OK
a37 -> a32 error!!!
a32 -> a25 error!!!
a37 -> a37 OK
a40 -> a40 OK
a25 -> a32 error!!!
a37 -> a37 OK
a41 -> a29 error!!!
a25 -> a25 OK
a29 -> a29 OK
a37 -> a37 OK
a40 -> a40 OK
a25 -> a25 OK
a25 -> a25 OK
a37 -> a25 error!!!
a25 -> a25 OK
a28 -> a28 OK
a42 -> a37 error!!!
a42 -> a42 OK
a28 -> a28 OK
a32 -> a25 err

IndexError: ignored

In [ ]:
correct = 0
for i in range(len(x)):
  print(y[i],"->",y_pred[i],end=' ')
if(x[i]==y_pred[i]):
  correct = correct + 1; print('OK')
else:
  print('error!!!')
  print("Correct: {} of {} accuracy = {:.2f}" .format(correct,len(x),correct/len(x)))

a25 -> a29 a25 -> a28 a25 -> a42 a25 -> a28 a25 -> a28 a25 -> a25 a25 -> a25 a25 -> a40 a25 -> a25 a25 -> a25 a25 -> a28 a25 -> a32 a25 -> a25 a25 -> a25 a25 -> a37 a25 -> a32 a25 -> a28 a25 -> a25 a25 -> a40 a25 -> a29 a25 -> a25 a25 -> a29 a25 -> a25 a25 -> a32 a25 -> a25 a25 -> a40 a25 -> a42 a25 -> a32 a25 -> a25 a25 -> a25 a25 -> a42 a25 -> a29 a25 -> a25 a25 -> a40 a25 -> a25 a25 -> a40 a25 -> a25 a25 -> a25 a25 -> a28 a25 -> a25 a25 -> a25 a25 -> a25 a25 -> a32 a25 -> a25 a25 -> a37 a25 -> a40 a25 -> a32 a25 -> a37 a25 -> a29 a25 -> a25 a25 -> a29 a25 -> a37 a25 -> a40 a25 -> a25 a25 -> a25 a25 -> a25 a25 -> a25 a25 -> a28 a25 -> a37 a25 -> a42 a25 -> a28 a25 -> a25 a25 -> a25 a25 -> a28 a25 -> a25 a25 -> a28 a25 -> a41 a25 -> a37 a25 -> a25 a25 -> a41 a25 -> a29 a25 -> a25 a25 -> a29 a25 -> a28 a25 -> a40 a25 -> a42 a25 -> a29 a25 -> a40 a25 -> a28 a25 -> a37 a25 -> a42 a25 -> a42 a25 -> a25 a25 -> a32 a25 -> a25 a25 -> a28 a25 -> a25 a25 -> a25 a25 -> a29 a25 -> a37 a25 -> a25

IndexError: ignored